# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [7]:
import numpy as np
array = np.arange(0,10)
array.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [13]:
arr1 = np.arange(0,10) 
arr1 = arr1.reshape(2,5)
arr2 = np.full((2,5),1)
arr3 = np.vstack((arr1,arr2))
arr3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [15]:
arr1 = np.arange(0,10) 
arr1 = arr1.reshape(2,5)
arr2 = np.full((2,5),1)
arr3 = np.hstack((arr1,arr2))
arr3

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [20]:
array = np.arange(0,10)
array = array.reshape(2,5)
# print(array)
print(array.flatten(order="C"))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [24]:
array = np.arange(0,15)
array = array.reshape((1,3,5))
array = array.ravel()
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [26]:
array = np.arange(0,15)
array = array.reshape((1,5,3))
array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [29]:
array = np.arange(0,25)
array = array.reshape((5,5))
square_array =np.square(array)
square_array

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [30]:
array = np.arange(0,30)
array = array.reshape((5,6))
array.mean()

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [31]:
array.std()

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [37]:
np.median(array)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [38]:
array.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [43]:
array = np.arange(0,16)
array = array.reshape(4,4)
np.trace(array)

30

## Question:13

### Find the determinant of the previous array in Q12?

In [45]:
from numpy.linalg import linalg
linalg.det(array)

-2.9582283945787796e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [49]:
print(np.percentile(array,5))
print(np.percentile(array,95))

0.75
14.25


## Question:15

### How to find if a given array has any null values?

In [52]:
np.isnan(array)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])